wallpaper {
    monitor = DP-3
    path = ~/.local/share/wallpapers/gruvbox-refraction.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.local/share/wallpapers/gruvbox-refraction.png
    fit_mode = cover
}

splash = false
ipc = true
