#!/bin/sh

xresource() {
    xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

#### AUTOSTART ####
exec $HOME/.scripts/autostart &

#### MONITOR ####
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM CONFIG ####
bspc config border_width         2
bspc config window_gap           8
bspc config active_border_color  $(xresource bblack)
bspc config normal_border_color  $(xresource bblack)
bspc config focused_border_color $(xresource blue)
# bspc config pointer_motion_interval 7ms

bspc config ignore_ewmh_focus    true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### RULES ####

bspc rule -a Steam desktop=4 state=floating
bspc rule -a VirtualBoxVM desktop=5 state=floating
bspc rule -a Mailspring desktop=6 follow=off
bspc rule -a Calcurse desktop=7
bspc rule -a TelegramDesktop desktop=8
bspc rule -a KotatogramDesktop desktop=8
bspc rule -a discord desktop=9 follow=off focus=off
bspc rule -a SpotifyTui desktop=10

# floting windows and others
bspc rule -a Pavucontrol state=floating
bspc rule -a UnityHub state=floating
bspc rule -a Peek state=floating
bspc rule -a Discover-overlay state=floating
bspc rule -a Nitrogen state=floating

# Other rules
bspc rule -a Plank layer=above manage=on border=off
