#! /bin/sh

#### AUTOSTART ####
xsetroot -cursor_name left_ptr &
pgrep -x nitrogen > /dev/null || nitrogen --restore &
pgrep -x dunst > /dev/null || dunst &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x pasystray > /dev/null || pasystray --volume-max 100 &
pgrep -x mictray > /dev/null || mictray &
pgrep -x xfce4-clipman > /dev/null || xfce4-clipman &
pgrep -x nm-applet > /dev/null || nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launchbspwm.sh &
pgrep -x xss-lock > /dev/null || xss-lock --transfer-sleep-lock -- i3lock --nofork -i $HOME/.local/share/wallpapers/arch-linux-wp-blur.png &

#### MONITOR ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM CONFIG ####
bspc config border_width          2
bspc config window_gap           12
bspc config active_border_color  "#7F8C8D"
bspc config normal_border_color  "#7F8C8D"
bspc config focused_border_color "#1D99F3"

bspc config ignore_ewmh_focus    true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### RULES ####

bspc rule -a Steam desktop=2 state=floating
bspc rule -a VirtualBoxVM desktop=5 state=floating
bspc rule -a Calcurse desktop=7
bspc rule -a TelegramDesktop desktop=8
bspc rule -a KotatogramDesktop desktop=8
bspc rule -a discord desktop=9
bspc rule -a SpotifyTui desktop=10

# floting windows
bspc rule -a Pavucontrol state=floating
bspc rule -a UnityHub state=floating
bspc rule -a Peek state=floating
