add_newline = false

[line_break]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = ".../"
